<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TINPNQ-DWX-0102" failures="1" tests="3" name="AKENEO" time="615.527" errors="0" timestamp="09 Jan 2020 06:32:42 GMT">
  <testcase classname="com.gcc.connector.Sanity.AKENEO" name="akeneoConnect" time="2.159"/>
  <testcase classname="com.gcc.connector.Sanity.AKENEO" name="submissionAKENEOstatus" time="613.143">
    <failure type="java.lang.AssertionError" message="expected [0] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [200]
at com.gcc.connector.Sanity.AKENEO.submissionAKENEOstatus(AKENEO.java:255)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- submissionAKENEOstatus -->
  <testcase classname="com.gcc.connector.Sanity.AKENEO" name="sessionterminatesTC" time="0.0">
    <skipped/>
  </testcase> <!-- sessionterminatesTC -->
</testsuite> <!-- AKENEO -->
